DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE NON_MEM CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE TICKETING CASCADE CONSTRAINTS;
DROP TABLE MOVIE CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE MEMBER_SHIP CASCADE CONSTRAINTS;
DROP TABLE QUESTION CASCADE CONSTRAINTS;
DROP TABLE CINEMA CASCADE CONSTRAINTS;
DROP TABLE SCREEN CASCADE CONSTRAINTS;
DROP TABLE REVIEW_COMMENT CASCADE CONSTRAINTS;
DROP TABLE THEATER CASCADE CONSTRAINTS;
DROP TABLE SEAT CASCADE CONSTRAINTS;
DROP TABLE CART_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;

CREATE TABLE MEMBER (
    MEM_CODE VARCHAR2(50) NOT NULL,
    MEM_NAME VARCHAR2(50) NOT NULL,
    MEM_SEX VARCHAR2(10) NOT NULL,
    MEM_BIRTH DATE NOT NULL,
    MEM_PHONE VARCHAR2(20) NOT NULL,
    MEM_ADDR VARCHAR2(200) NOT NULL,
    MEM_EMAIL VARCHAR2(100) NOT NULL,
    MEM_ID VARCHAR2(100) NOT NULL,
    MEM_PWD VARCHAR2(100) NOT NULL,
    PRIMARY KEY (MEM_CODE),
    UNIQUE (MEM_PHONE, MEM_EMAIL, MEM_ID)
);

CREATE TABLE NON_MEM (
    NON_MEM_CODE VARCHAR2(50) NOT NULL,
    NON_MEM_NAME VARCHAR2(50) NOT NULL,
    NON_MEM_PHONE VARCHAR2(20) NOT NULL,
    NON_MEM_BIRTH DATE NOT NULL,
    NON_MEM_PWD VARCHAR2(100) NOT NULL,
    PRIMARY KEY (NON_MEM_CODE),
    UNIQUE (NON_MEM_PHONE)
);

CREATE TABLE PRODUCT (
    PRODUCT_SEQ NUMBER(10) NOT NULL,
    PRODUCT_CATEGORY VARCHAR2(20) NOT NULL,
    PRODUCT_NAME VARCHAR2(50) NOT NULL,
    PRODUCT_PRICE NUMBER(10) NOT NULL,
    PRODUCT_STOCK NUMBER(10) NOT NULL,
    PRIMARY KEY (PRODUCT_SEQ)
);

CREATE TABLE TICKETING (
    TICKET_SEQ NUMBER(10) NOT NULL,
    TICKET_DATE DATE NOT NULL,
    TICKET_NUM NUMBER(10) NOT NULL,
    TICKET_PRICE NUMBER(10) NOT NULL,
    MEM_CODE VARCHAR2(50),
    NON_MEM_CODE VARCHAR2(50),
    SCREEN_CODE VARCHAR2(50) NOT NULL,
    PRIMARY KEY (TICKET_SEQ)
);

CREATE TABLE MOVIE (
    MOVIE_CODE VARCHAR2(50) NOT NULL,
    MOVIE_TITLE VARCHAR2(100) NOT NULL,
    MOVIE_SPECTATOR NUMBER(2) NOT NULL,
    PRIMARY KEY (MOVIE_CODE)
);

CREATE TABLE REVIEW (
    REVIEW_SEQ NUMBER(10) NOT NULL,
    REVIEW_WRITER VARCHAR2(50) NOT NULL,
    REVIEW_DATE DATE NOT NULL,
    REVIEW_TITLE VARCHAR2(100) NOT NULL,
    REVIEW_CONTENT VARCHAR2(1000) NOT NULL,
    REVIEW_STAR NUMBER(1) NOT NULL,
    MEM_CODE VARCHAR2(50),
    MOVIE_CODE VARCHAR2(50),
    PRIMARY KEY (REVIEW_SEQ)
);

CREATE TABLE CART (
    CART_SEQ NUMBER(10) NOT NULL,
    CART_SUM_PRICE NUMBER(10) NOT NULL,
    MEM_CODE VARCHAR2(50) NOT NULL,
    PRIMARY KEY (CART_SEQ)
);

CREATE TABLE MEMBER_SHIP (
    MEM_CODE VARCHAR2(50) NOT NULL,
    SHIP_SEQ NUMBER(10) NOT NULL,
    SHIP_RATING VARCHAR2(50) NOT NULL,
    PRIMARY KEY (MEM_CODE)
);

CREATE TABLE QUESTION (
    QST_SEQ NUMBER(10) NOT NULL,
    QST_WRITER VARCHAR2(50) NOT NULL,
    QST_TITLE VARCHAR2(100) NOT NULL,
    QST_CONTENT VARCHAR2(1000) NOT NULL,
    QST_FILE BLOB NOT NULL,
    QST_CATEGORY VARCHAR2(20) NOT NULL,
    MEM_CODE VARCHAR2(50),
    NON_MEM_CODE VARCHAR2(50),
    PRIMARY KEY (QST_SEQ)
);

CREATE TABLE CINEMA (
    CINEMA_CODE VARCHAR2(50) NOT NULL,
    CINEMA_NAME VARCHAR2(50) NOT NULL,
    CINEMA_LOCATION VARCHAR2(50) NOT NULL,
    PRIMARY KEY (CINEMA_CODE),
    UNIQUE (CINEMA_NAME)
);

CREATE TABLE SCREEN (
    SCREEN_CODE VARCHAR2(50) NOT NULL,
    SCREEN_DATE DATE NOT NULL,
    SCREEN_TIME TIMESTAMP NOT NULL,
    MOVIE_CODE VARCHAR2(50) NOT NULL,
    THEATER_CODE VARCHAR2(50) NOT NULL,
    PRIMARY KEY (SCREEN_CODE)
);

CREATE TABLE REVIEW_COMMENT (
    RC_SEQ NUMBER(10) NOT NULL,
    RC_WRITER VARCHAR2(50) NOT NULL,
    RC_DATE DATE NOT NULL,
    RC_CONTENT VARCHAR2(1000) NOT NULL,
    RC_PARENT_SEQ NUMBER(10) NOT NULL,
    PRIMARY KEY (RC_SEQ)
);

CREATE TABLE THEATER (
    THEATER_CODE VARCHAR2(50) NOT NULL,
    THEATER_NAME VARCHAR2(50) NOT NULL,
    THEATER_SEAT_NUM NUMBER(10) NOT NULL,
    CINEMA_CODE VARCHAR2(50) NOT NULL,
    PRIMARY KEY (THEATER_CODE)
);

CREATE TABLE SEAT (
    SEAT_CODE VARCHAR2(50) NOT NULL,
    SEAT_ROW VARCHAR2(2) NOT NULL,
    SEAT_COL NUMBER(2) NOT NULL,
    SEAT_STATUS VARCHAR2(20) NOT NULL,
    THEATER_CODE VARCHAR2(50) NOT NULL,
    PRIMARY KEY (SEAT_CODE)
);

CREATE TABLE CART_PRODUCT (
    CART_SEQ NUMBER(10) NOT NULL,
    PRODUCT_SEQ NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    PRIMARY KEY (CART_SEQ, PRODUCT_SEQ)
);

CREATE TABLE PAYMENT (
    PAY_SEQ NUMBER(10) NOT NULL,
    PAY_PRICE NUMBER(10) NOT NULL,
    PAY_DATE DATE NOT NULL,
    PAY_METHOD VARCHAR2(20) NOT NULL,
    MEM_CODE VARCHAR2(50),
    NON_MEM_CODE VARCHAR2(50),
    PRIMARY KEY (PAY_SEQ)
);

ALTER TABLE TICKETING ADD FOREIGN KEY (MEM_CODE) REFERENCES MEMBER(MEM_CODE);
ALTER TABLE TICKETING ADD FOREIGN KEY (NON_MEM_CODE) REFERENCES NON_MEM(NON_MEM_CODE);
ALTER TABLE TICKETING ADD FOREIGN KEY (SCREEN_CODE) REFERENCES SCREEN(SCREEN_CODE);
ALTER TABLE REVIEW ADD FOREIGN KEY (MEM_CODE) REFERENCES MEMBER(MEM_CODE);
ALTER TABLE REVIEW ADD FOREIGN KEY (MOVIE_CODE) REFERENCES MOVIE(MOVIE_CODE);
ALTER TABLE CART ADD FOREIGN KEY (MEM_CODE) REFERENCES MEMBER(MEM_CODE);
ALTER TABLE MEMBER_SHIP ADD FOREIGN KEY (MEM_CODE) REFERENCES MEMBER(MEM_CODE);
ALTER TABLE QUESTION ADD FOREIGN KEY (MEM_CODE) REFERENCES MEMBER(MEM_CODE);
ALTER TABLE QUESTION ADD FOREIGN KEY (NON_MEM_CODE) REFERENCES NON_MEM(NON_MEM_CODE);
ALTER TABLE SCREEN ADD FOREIGN KEY (MOVIE_CODE) REFERENCES MOVIE(MOVIE_CODE);
ALTER TABLE SCREEN ADD FOREIGN KEY (THEATER_CODE) REFERENCES THEATER(THEATER_CODE);
ALTER TABLE REVIEW_COMMENT ADD FOREIGN KEY (RC_PARENT_SEQ) REFERENCES REVIEW_COMMENT(RC_SEQ);
ALTER TABLE THEATER ADD FOREIGN KEY (CINEMA_CODE) REFERENCES CINEMA(CINEMA_CODE);
ALTER TABLE SEAT ADD FOREIGN KEY (THEATER_CODE) REFERENCES THEATER(THEATER_CODE);
ALTER TABLE CART_PRODUCT ADD FOREIGN KEY (PRODUCT_SEQ) REFERENCES PRODUCT(PRODUCT_SEQ);
ALTER TABLE CART_PRODUCT ADD FOREIGN KEY (CART_SEQ) REFERENCES CART(CART_SEQ);
ALTER TABLE PAYMENT ADD FOREIGN KEY (MEM_CODE) REFERENCES MEMBER(MEM_CODE);
ALTER TABLE PAYMENT ADD FOREIGN KEY (NON_MEM_CODE) REFERENCES NON_MEM(NON_MEM_CODE);